### ISSUE TITLE
No such package @zig_sdk//platform on 1.0.1

### ISSUE THREAD

**Issue by Gentatsu** [uber/bazel-zig-cc#25]
Getting this on compilation using the upgraded package:
```
 com.google.devtools.build.lib.packages.RepositoryFetchException: no such package '@zig_sdk//platform': compilation failed:
return_code=1
stderr=
stdout=launcher.zig:296:19: error: expected ')', found ','
    for (want_args, res.exec.args.items) |want_arg, got_arg|
```

Looks like a simple syntax error.

FWIW, 1.0.0 still works fine :)

**Comment by motiejus** [comment]
This is a new feature in zig: https://kristoff.it/blog/zig-multi-sequence-for-loops/ which the launcher uses.

Looks like you upgraded bazel-zig-cc but did not upgrade Zig?

As of bazel-zig-cc v1.0.1 it is recommended to use `zig_toolchains()` without parameters, unless you want to mirror Zig SDK yourself instead of downloading it from mirror.bazel.build. But then you will need to track such issues yourself and upgrade Zig from time to time.

**Comment by Gentatsu** [comment]
Aye, that worked. Thanks mate.
